#!/bin/sh

set -eu

if [ -z "${IMAGE:-}" ]; then
	echo "IMAGE must be declared" >&2
	exit 1
fi

if ! [ -f "$1" ] && ! [ -d "$1" ]; then
	echo "Usage: $0 <test|dir of test>" >&2
	exit 1
fi

TOSTRIPID="$(docker create "$IMAGE")"

docker export "$TOSTRIPID" > working.tar

docker rm -vf "$TOSTRIPID" >/dev/null

: > toinclude.txt

# start loop

TOSTRIPID=""
while true; do

cp working.tar tostrip.tar

file="$( (tar -tf tostrip.tar ; cat toinclude.txt) | sort | uniq -u | head -n 1)" || true

[ -z "$file" ] && break

printf "Removing %s" "$file"
tar --delete -f tostrip.tar "$file"

if [ -n "$TOSTRIPID" ]; then
	docker rmi "$TOSTRIPID" >/dev/null 2>/dev/null || true
fi
TOSTRIPID="$(docker import tostrip.tar 2>/dev/null)"
printf "."
export TOSTRIPID

ret=0
"$1" || ret=$?
printf "."

if [ "$ret" = 0 ]; then
	mv tostrip.tar working.tar
	printf "success\n"
else
	echo "$file" >> toinclude.txt
	printf "fail, including\n"
fi

done
